<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="beige-paper.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MemeCalcBackEnd\MemeCalcBackEnd.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="beige-paper.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
